## 数据操作


In [2]:
import torch

In [8]:
x = torch.arange(12)#arange生成0~12一共13个数
x

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [9]:
#shape属性访问张量的形状和元素总数
x.shape

torch.Size([12])

In [10]:
x.numel()#标量，张量中元素总数

12

In [ ]:
x = x.reshape(3,4)#改变张量的形状
x

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

In [12]:
#全0、全1
torch.zeros((2,3,4))#创建一个2*3*4的全0张量

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [13]:
torch.ones((2,3,4))#创建一个2*3*4的全1张量

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])

In [15]:
x = torch.tensor([1.0,2,4,8])
y = torch.tensor([2,3,4,5])
x + y, x - y, x * y, x / y

(tensor([ 3.,  5.,  8., 13.]),
 tensor([-1., -1.,  0.,  3.]),
 tensor([ 2.,  6., 16., 40.]),
 tensor([0.5000, 0.6667, 1.0000, 1.6000]))

In [ ]:
#多个张量连结
x = torch.arange(12,dtype=torch.float32).reshape(3,4)
y = torch.tensor([[2.0,1,2,3],[4,5,6,7],[8,9,10,11]])
torch.cat((x,y),dim=0), torch.cat((x,y),dim=1)#dim=0表示按行连结，dim=1表示按列连结

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [ 2.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.]]),
 tensor([[ 0.,  1.,  2.,  3.,  2.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.,  4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.,  8.,  9., 10., 11.]]))

In [ ]:
x == y#逐元素比较

tensor([[False,  True,  True,  True],
        [ True,  True,  True,  True],
        [ True,  True,  True,  True]])

In [ ]:
#sum（）求和，产生只有一个元素的张量
x.sum()
y.sum()
print(y.sum(), x.sum())

tensor(68.) tensor(66.)


In [23]:
#广播机制
a = torch.arange(3).reshape(3,1)
b = torch.arange(2).reshape(1,2)
a, b

(tensor([[0],
         [1],
         [2]]),
 tensor([[0, 1]]))

In [24]:
a + b

tensor([[0, 1],
        [1, 2],
        [2, 3]])

##### a          b    广播机制
##### 0 0   0 1
##### 1 1   0 1
##### 2 2   0 1

In [25]:
# 执行原地操作
z = torch.zeros_like(y)
print('id(z):', id(z))
z[:] = x + y
print('id(z):',id(z))

id(z): 1649418411584
id(z): 1649418411584


In [26]:
a = torch.tensor([3.6])
a, a.item(), float(a), int(a)

(tensor([3.6000]), 3.5999999046325684, 3.5999999046325684, 3)

In [27]:
#数据预处理
import os

os.makedirs(os.path.join('data'),exist_ok=True)
data_file = os.path.join('data','house_tiny.csv')
with open(data_file, 'w') as f:
    f.write('NumRooms,Alley,Price\n')#列名
    f.write('NA,Pave,127500\n')#每行表示一共数据样本
    f.write('2,NA,106000\n')
    f.write('4,NA,178100\n')
    f.write('3,NA,140000\n')

In [30]:
#从创建的csv文件中加载原始数据集
import pandas as pd

data = pd.read_csv(data_file)
data

NumRooms Alley   Price
0       NaN  Pave  127500
1       2.0   NaN  106000
2       4.0   NaN  178100
3       3.0   NaN  140000

In [ ]:
#处理缺失值，插值或删除，通常考虑插值
inputs, outputs = data.iloc[:,0:2], data.iloc[:,2]
inputs = inputs.fillna(inputs.mean(numeric_only=True))#用均值填充缺失值，参数numeric_only=True，表示只计算数值列的平均值，忽略非数值列（如字符串列）。
print(inputs)

   NumRooms Alley
0       3.0  Pave
1       2.0   NaN
2       4.0   NaN
3       3.0   NaN


In [39]:
#对于inputs中的类别值和离散值，将nan视为一个类别
inputs = pd.get_dummies(inputs, dummy_na=True)
print(inputs)

   NumRooms  Alley_Pave  Alley_nan
0       3.0        True      False
1       2.0       False       True
2       4.0       False       True
3       3.0       False       True
