In [1]:
import torch
_ = torch.tensor([0.2126, 0.7152, 0.0722], names=['c'])

C:\Users\QDWL\AppData\Local\Temp\ipykernel_5928\1646494204.py:2: UserWarning: Named tensors and all their associated APIs are an experimental feature and subject to change. Please do not use them for anything important until they are released as stable. (Triggered internally at C:\cb\pytorch_1000000000000\work\c10/core/TensorImpl.h:1931.)
  _ = torch.tensor([0.2126, 0.7152, 0.0722], names=['c'])


In [ ]:
img_t = torch.randn(3, 5, 5) # shape [channels维数, rows行, columns列]，用于生成随机张量的函数，服从标准正态分布（均值为 0，标准差为 1）的随机数张量
weights = torch.tensor([0.2126, 0.7152, 0.0722])
img_t #三维张量

tensor([[[ 0.9542, -0.9012,  0.0831, -0.3821, -0.6480],
         [ 0.7985, -0.3339, -0.5712,  1.2871,  1.0817],
         [-0.3204,  0.0968, -0.2561,  0.8989, -0.2045],
         [-0.1707,  0.4700,  0.4135,  0.2341,  1.4344],
         [-0.4470,  0.4182,  1.7584, -1.0786, -0.8606]],

        [[ 1.1031,  1.2693, -1.8597,  1.2151,  0.4968],
         [ 0.1623, -1.1615, -0.1872, -0.2884, -2.0722],
         [-0.7652, -0.4592, -0.8339, -0.3828,  1.1525],
         [-0.8116,  1.3083,  0.2785, -0.1407, -0.7020],
         [-0.2769,  1.4093,  0.3402, -0.9230, -0.1275]],

        [[ 0.1218,  0.0574, -0.7166,  1.6954, -0.8314],
         [-0.3943, -0.3404,  1.2764, -1.3080, -0.2795],
         [-0.1643, -0.7239, -0.7758, -0.2889, -0.8772],
         [ 0.9169,  0.3900, -0.2301,  0.4945,  2.0770],
         [-0.5409, -2.3484, -1.0329, -0.3352,  2.0201]]])

In [3]:
batch_t = torch.randn(2, 3, 5, 5) # shape [batch批次, channels, rows, columns]
batch_t #四维张量

tensor([[[[ 1.9012, -0.1780,  0.7546, -0.6673, -0.3663],
          [-1.1040,  0.6771,  2.4503, -0.0388, -0.6577],
          [-0.0238, -0.5974,  1.7691, -0.8815, -1.1778],
          [-0.6891, -0.2285,  0.1693,  0.0133, -0.3430],
          [-0.7639, -0.2665, -0.0880,  1.3487,  1.4801]],

         [[ 1.1701, -3.0089,  0.3284, -0.0225,  1.8567],
          [-2.1814, -1.7265,  0.7501,  0.8389,  1.6873],
          [ 0.0440,  1.7818,  0.1747, -1.3513, -2.1780],
          [ 0.3053, -0.3602, -2.0621, -0.4813, -0.5079],
          [-1.5215,  0.5540, -1.3409,  0.3991, -1.2494]],

         [[ 1.2376, -0.5921, -0.0315,  0.3290,  0.1928],
          [-0.1174, -0.3246,  1.0015, -1.4027,  1.2589],
          [ 1.1429,  0.8637,  0.4978,  0.1482, -0.0428],
          [ 0.0721,  0.3173,  0.7341, -0.0490,  1.1188],
          [-0.6210, -0.5904, -0.4715,  0.9921,  0.2002]]],


        [[[-0.7498,  0.2067, -0.6717,  1.5461, -0.8804],
          [ 0.5028,  0.7367,  0.1360,  0.6174, -1.3080],
          [ 1.2613, -0.

In [4]:
img_gray_naive = img_t.mean(-3)
batch_gray_naive = batch_t.mean(-3)
img_gray_naive.shape, batch_gray_naive.shape

(torch.Size([5, 5]), torch.Size([2, 5, 5]))

In [5]:
unsqueezed_weights = weights.unsqueeze(-1).unsqueeze_(-1)
img_weights = (img_t * unsqueezed_weights)
batch_weights = (batch_t * unsqueezed_weights)
img_gray_weighted = img_weights.sum(-3)
batch_gray_weighted = batch_weights.sum(-3)
batch_weights.shape, batch_t.shape, unsqueezed_weights.shape

(torch.Size([2, 3, 5, 5]), torch.Size([2, 3, 5, 5]), torch.Size([3, 1, 1]))

In [ ]:
img_gray_weighted_fancy = torch.einsum('...chw,c->...hw', img_t, weights)
batch_gray_weighted_fancy = torch.einsum('...chw,c->...hw', batch_t, weights)
batch_gray_weighted_fancy.shape

tensor([[[ 1.3304, -2.2326,  0.3930, -0.1342,  1.2640],
         [-1.8033, -1.1142,  1.1297,  0.4905,  1.1578],
         [ 0.1089,  1.2097,  0.5370, -1.1432, -1.8112],
         [ 0.0771, -0.2833, -1.3858, -0.3449, -0.3554],
         [-1.2955,  0.2970, -1.0117,  0.6438, -0.5644]],

        [[-0.1906,  0.2461, -0.2065,  0.3724,  0.6712],
         [-0.3823,  1.4944, -1.4021, -0.3125, -1.0214],
         [-0.2747,  0.5402,  0.0840,  0.4827, -0.9922],
         [-0.0110, -0.0729,  0.4731,  0.3723,  1.5473],
         [ 1.5165, -0.4362, -0.1776,  0.0525, -0.2259]]])


torch.Size([2, 5, 5])

In [6]:
weights_named = torch.tensor([0.2126, 0.7152, 0.0722], names=['channels'])
weights_named

tensor([0.2126, 0.7152, 0.0722], names=('channels',))

In [8]:
img_named =  img_t.refine_names(..., 'channels', 'rows', 'columns')
batch_named = batch_t.refine_names(..., 'channels', 'rows', 'columns')
print("img named:", img_named.shape, img_named.names)
print("batch named:", batch_named.shape, batch_named.names)

img named: torch.Size([3, 5, 5]) ('channels', 'rows', 'columns')
batch named: torch.Size([2, 3, 5, 5]) (None, 'channels', 'rows', 'columns')


In [9]:
weights_aligned = weights_named.align_as(img_named)
weights_aligned.shape, weights_aligned.names

(torch.Size([3, 1, 1]), ('channels', 'rows', 'columns'))

In [10]:
gray_named = (img_named * weights_aligned).sum('channels')
gray_named.shape, gray_named.names

(torch.Size([5, 5]), ('rows', 'columns'))

In [11]:
try:
    gray_named = (img_named[..., :3] * weights_named).sum('channels')
except Exception as e:
    print(e)

Error when attempting to broadcast dims ['channels', 'rows', 'columns'] and dims ['channels']: dim 'columns' and dim 'channels' are at the same position from the right but do not match.


In [12]:
gray_plain = gray_named.rename(None)
gray_plain.shape, gray_plain.names

(torch.Size([5, 5]), (None, None))